import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import  {Toaster} from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/auth/providers/theme-providers";
import { cn } from "@/lib/utils";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        {/* <body
          className={cn(
            geistSans.variable,
            geistMono.variable,
            " bg-black antialiased"
          )}
        > */}
         <body
          className={cn(geistSans.variable, geistMono.variable, "bg-white dark:bg-[#121212]")}
        >
          <Toaster />
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey="theme"
            
          >
            {children}
          </ThemeProvider>
       
        </body>
      </html>
    </SessionProvider>
  );
}
